
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/01_matmul.ipynb

from exp.nb_00 import *
import operator

def test(a, b, cmp, cname=None):
    if cname is None: cname==cmp.__name__
    assert cmp(a,b),f"{cname}:\n{a}\n{b}"

def test_eq(a,b): test(a,b, operator.eq, "==")

from pathlib import Path
from IPython.core.debugger import set_trace
import pickle, gzip, math
import tensorflow as tf
import matplotlib.pyplot as plt
import matplotlib as mpl
from tensorflow import Tensor

MNIST_URL = 'http://deeplearning.net/data/mnist/mnist.pkl.gz'

def allclose(x, y, rtol=1e-5, atol=1e-8):
    return tf.reduce_all(tf.abs(x - y) <= tf.abs(y) * rtol + atol)
def near(a,b): return allclose(a, b, rtol=1e-3, atol=1e-5)
def test_near(a,b): test(a,b,near)