
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/03_minibatch_training.ipynb

from exp.nb_02 import *

def accuracy(out, yb): return tf.reduce_mean(tf.cast(tf.math.equal(tf.argmax(out, axis=1), yb), 'float'))

from tensorflow.keras import optimizers

class Dataset():
    def __init__(self, x, y): self.x, self.y = x,y
    def __len__(self): return len(self.x)
    def __getitem__(self, i): return self.x[i], self.y[i]

def get_dls(train_ds, valid_ds, bs, **kwargs):
    return (tf.data.Dataset.from_tensor_slices((train_ds.x, train_ds.y), **kwargs).batch(bs).shuffle(True),
            tf.data.Dataset.from_tensor_slices((valid_ds.x, valid_ds.y), **kwargs).batch(bs))