
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/02_fully_connected.ipynb

from exp.nb_01 import *

def get_data():
    path = tf.keras.utils.get_file('mnist.pkl.gz', MNIST_URL, archive_format='.gz')
    with gzip.open(path, 'rb') as f:
        ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding='latin-1')
    return map(tf.convert_to_tensor, (x_train, y_train, x_valid, y_valid))

def normalize(x, m, s): return (x-m)/s

def test_near_zero(a, tol=1e-3): assert tf.abs(a)<tol, f"Near zero: {a}"

def mse(output, targ): return tf.reduce_mean(tf.math.pow(tf.squeeze(output, -1) - targ, 2))

from tensorflow.keras import layers